/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 14c7fdcb203c80fa2a562a3b5f4b46e9)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	PRIVATE_ASSETS: R2Bucket;
	DB: D1Database;
	LARGE_RECOVERY_QUEUE: Queue;
	ASSETS: Fetcher;
	AUTH_MODE: string;
	NEXT_PUBLIC_AUTH_MODE: string;
	CRM_LOG_LEVEL: string;
	CLOUD_AUTOMATIC_BACKUP_ENABLED: string;
	CLOUD_LARGE_RECOVERY_ENABLED: string;
	EMAIL_DELIVERY_ENABLED: string;
	EMAIL_FROM: string;
	BETTER_AUTH_URL: string;
	CORS_ALLOWED_EXTENSION_IDS: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./custom-worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./custom-worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_MODE" | "NEXT_PUBLIC_AUTH_MODE" | "CRM_LOG_LEVEL" | "CLOUD_AUTOMATIC_BACKUP_ENABLED" | "CLOUD_LARGE_RECOVERY_ENABLED" | "EMAIL_DELIVERY_ENABLED" | "EMAIL_FROM" | "BETTER_AUTH_URL" | "CORS_ALLOWED_EXTENSION_IDS">> {}
}
