import { expect, test, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import type { CalendarEventFacts, CalendarEventLinkPreview, SavedCalendarEvent, SavedCalendarEventReview } from '../../packages/domain/src/calendar-events';
const connectionId = 'dd34bba6-a7d2-4f18-a862-958733f456b5', publicId = 'b32a7fce-6d20-43b3-9ee7-f05a38a1e6d9', epoch = 'b5cac8f4-758f-442c-8faa-a36a8915d5f4', generation = 'dce4ac26-e549-4bff-a92a-c3f583805544', calendarId = 'personal@example.test';
const source = '**/api/connections/' + connectionId + '/calendars/events', url = `/connections/google/${connectionId}/calendars/events/link?${new URLSearchParams({ calendar_id: calendarId, event_id: 'meeting' })}`;
const person = { id: 1, name: 'Ana One', email: 'shared@example.test' }, other = { id: 2, name: 'Ana Two', email: 'shared@example.test' }, plan = { id: 3, summary: 'Call Ana', contact_id: 1, contact_name: 'Ana One', planned_date: '2026-10-05' };
function facts(): CalendarEventFacts { return { id: 'meeting', status: 'confirmed', title: 'Lunch with Ana · relações', location: 'Café Lisboa', visibility: 'default', redacted: false, event_type: 'default',
  start: { date: null, date_time: '2026-10-04T12:00:00+01:00', time_zone: 'Europe/Lisbon', instant: '2026-10-04T11:00:00Z' }, end: { date: null, date_time: '2026-10-04T13:00:00+01:00', time_zone: 'Europe/Lisbon', instant: '2026-10-04T12:00:00Z' }, original_start: null, recurring_id: null, ical_uid: null, updated: null, etag: null,
  organizer: null, attendees: [{ email: 'shared@example.test', name: 'Ana', self: false, resource: false, organizer: false, response: 'accepted' }], attendees_incomplete: false, google_url: 'https://calendar.google.com/calendar/event?eid=meeting', conference_url: null }; }
function saved(): SavedCalendarEvent { return { public_id: publicId, revision: 3, calendar_label: 'Personal', calendar_time_zone: 'Europe/Lisbon', account_email: 'owner@example.test', observed_at: '2026-10-04T10:00:00Z', source_status: 'available', facts: facts(), people: [{ id: 1, name: 'Ana One' }], plans: [plan] }; }
function preview(): CalendarEventLinkPreview { return { epoch, authorization_revision: 1, selection_revision: 2, generation, calendar_label: 'Personal', calendar_time_zone: 'Europe/Lisbon', account_email: 'owner@example.test', observed_at: '2026-10-04T10:00:00Z', facts: facts(), saved: null, matches: [{ address: 'shared@example.test', candidates: [person, other], more: false }], contacts: [person, other], plans: [plan], contacts_more: false, contacts_next: null, plans_more: false, plans_next: null }; }
async function login(page: Page) {
  await page.request.post('/api/auth/login', { data: { password: 'bonds-e2e-account-password' } });
  await page.route('**/api/auth/get-session*', (route) => route.fulfill({ json: { session: null, user: null } }));
}
test('Event links require explicit ambiguous matches and confirmation, fit mobile and pass accessibility', async ({ page }, info) => {
  await login(page); let data = preview(), saves = 0; const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.route(source + '/link-preview?*', (route) => route.fulfill({ json: data }));
  await page.route(source + '/link', async (route) => { const body = route.request().postDataJSON(); expect(body.contact_ids).toEqual([1]); expect(body.plan_ids).toEqual([3]); expect(body.expected_event_revision).toBeNull(); expect(body.expected_generation).toBe(generation); expect(Object.keys(body)).toHaveLength(10); expect(JSON.stringify(body)).not.toContain('facts'); saves++; data = { ...data, saved: saved() }; await route.fulfill({ json: { event: saved(), removed: false } }); });
  await page.goto(url); await expect(page.getByText('shared@example.test: Ana One, Ana Two')).toBeVisible();
  expect(await page.getByRole('checkbox').count()).toBe(3); await expect(page.getByRole('checkbox', { name: 'Ana One · shared@example.test' })).not.toBeChecked();
  await page.getByRole('checkbox', { name: 'Ana One · shared@example.test' }).check(); await page.getByRole('checkbox', { name: 'Call Ana · Ana One · 2026-10-05' }).check();
  await page.getByRole('button', { name: 'Save reviewed context' }).click(); expect(saves).toBe(0); const dialog = page.getByRole('alertdialog', { name: 'Save this event context?' }); await expect(dialog).toContainText('1 person and 1 plan'); await expect(dialog).toContainText('does not change plan dates'); await dialog.getByRole('button', { name: 'Confirm event links' }).click();
  await expect(page.getByText('Event context saved. Plans and interaction history are unchanged.')).toBeVisible(); await expect(page.getByRole('link', { name: 'Open retained context' })).toHaveAttribute('href', '/calendar/events/' + publicId); expect(saves).toBe(1);
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([]); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.evaluate(() => scrollTo(0, 0)); await page.screenshot({ path: info.outputPath('event-links.png'), fullPage: true }); expect(errors).toEqual([]);
});
test('Lost acknowledgement survives reload and retries the exact source choices without duplicating an event', async ({ page }) => {
  await login(page); let data = preview(), first = '', effects = 0, requests = 0;
  await page.route(source + '/link-preview?*', (route) => route.fulfill({ json: data }));
  await page.route(source + '/link', async (route) => { requests++; const payload = route.request().postData()!; if (!first) { first = payload; effects++; data = { ...data, saved: saved() }; await route.fulfill({ status: 503, json: { error: 'Acknowledgement lost' } }); } else { expect(payload).toBe(first); await route.fulfill({ json: { event: saved(), removed: false } }); } });
  await page.goto(url); await page.getByRole('checkbox', { name: 'Ana One · shared@example.test' }).check(); await page.getByRole('checkbox', { name: 'Call Ana · Ana One · 2026-10-05' }).check(); await page.getByRole('button', { name: 'Save reviewed context' }).click(); await page.getByRole('button', { name: 'Confirm event links' }).click();
  await expect(page.getByRole('button', { name: 'Retry unchanged event change' })).toBeVisible(); await expect(page.getByRole('checkbox', { name: 'Ana Two · shared@example.test' })).toBeDisabled(); await page.reload(); await expect(page.getByRole('button', { name: 'Retry unchanged event change' })).toBeVisible();
  await page.getByRole('button', { name: 'Retry unchanged event change' }).click(); await expect(page.getByRole('button', { name: 'Retry unchanged event change' })).toHaveCount(0); expect([effects, requests]).toEqual([1, 2]); await expect(page.getByRole('checkbox', { name: 'Ana One · shared@example.test' })).toBeChecked();
});
test('Retained context supports later links while disconnected, preserves searched choices and recovers uncertain removal', async ({ page }) => {
  await login(page); let event = { ...saved(), source_status: 'review_required' as const }, attempts = 0, deletes = 0, frozen = ''; const endpoint = '**/api/calendar/events/' + publicId;
  await page.route(endpoint + '?*', async (route) => { const search = new URL(route.request().url()).searchParams.get('search'); const data: SavedCalendarEventReview = { epoch, event, contacts: search ? [other] : [person, other], plans: [plan], contacts_more: false, contacts_next: null, plans_more: false, plans_next: null }; await route.fulfill({ json: data }); });
  await page.route(endpoint, async (route) => {
    if (route.request().method() === 'DELETE') { deletes++; const payload = route.request().postData()!; if (!frozen) { frozen = payload; await route.fulfill({ status: 503, json: { error: 'Recovery point could not be verified yet' } }); } else { expect(payload).toBe(frozen); await route.fulfill({ json: { event: null, removed: true } }); } return; }
    attempts++; const body = route.request().postDataJSON(); expect(body.contact_ids).toEqual([1, 2]); expect(body.plan_ids).toEqual([3]); if (attempts === 1) { event = { ...event, revision: 5 }; await route.fulfill({ status: 409, json: { error: 'Event changed. Refresh while keeping your choices.' } }); } else { expect(body.expected_revision).toBe(5); event = { ...event, revision: 8, people: [person, other].map(({ id, name }) => ({ id, name })) }; await route.fulfill({ json: { event, removed: false } }); }
  });
  await page.goto('/calendar/events/' + publicId); await expect(page.getByText('Retained context may be out of date.', { exact: false })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Ana Two · shared@example.test' }).check(); await page.getByLabel('Search people or plans').fill('Ana Two'); await page.getByRole('button', { name: 'Search event links' }).click(); await expect(page.getByRole('checkbox', { name: 'Ana One', exact: true })).toBeChecked();
  await page.getByRole('button', { name: 'Save reviewed context' }).click(); await page.getByRole('button', { name: 'Confirm event links' }).click(); await expect(page.getByRole('alert').filter({ hasText: 'Event changed' })).toContainText('Event changed'); await page.getByRole('button', { name: 'Refresh current event' }).click(); await expect(page.getByRole('checkbox', { name: 'Ana Two · shared@example.test' })).toBeChecked();
  await page.getByRole('button', { name: 'Save reviewed context' }).click(); await page.getByRole('button', { name: 'Confirm event links' }).click(); await expect(page.getByText('Event context saved.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Remove saved context' }).click(); const dialog = page.getByRole('alertdialog', { name: 'Remove saved event context?' }); await expect(dialog).toContainText('verified CRM recovery point'); await dialog.getByRole('button', { name: 'Confirm context removal' }).click(); await expect(page.getByRole('button', { name: 'Retry unchanged event change' })).toBeVisible(); await page.reload(); await page.getByRole('button', { name: 'Retry unchanged event change' }).click(); await expect(page.getByText('Saved context removed. People and plans remain intact.')).toBeVisible(); expect([attempts, deletes]).toEqual([2, 2]);
});
test('A person view lists plan-derived context and links to retained review', async ({ page }) => {
  await login(page); await page.route('**/api/calendar/events?*', (route) => { expect(new URL(route.request().url()).searchParams.get('contact_id')).toBe('1'); return route.fulfill({ json: { events: [{ ...saved(), people: [] }], more: false, next: null } }); });
  await page.goto('/calendar/events?contact_id=1'); await expect(page.getByRole('heading', { name: 'Saved calendar context' })).toBeVisible(); await expect(page.getByText('Linked people: none.')).toBeVisible(); await expect(page.getByRole('link', { name: 'Call Ana · Ana One · 2026-10-05' })).toHaveAttribute('href', '/contacts/1'); await expect(page.getByRole('link', { name: 'Review saved links' })).toHaveAttribute('href', '/calendar/events/' + publicId);
});

test('Recovery clears both an unconfirmed operation and stale person/plan choices instead of reusing restored integer IDs', async ({ page }) => {
  await login(page); let currentEpoch = epoch, event = saved(), restoring = false;
  const endpoint = '**/api/calendar/events/' + publicId;
  await page.route(endpoint + '?*', (route) => route.fulfill({ json: { epoch: currentEpoch, event, contacts: restoring ? [{ ...person, name: 'A different restored person' }] : [person, other], plans: [plan], contacts_more: false, contacts_next: null, plans_more: false, plans_next: null } }));
  await page.route(endpoint, (route) => route.fulfill({ status: 503, json: { error: 'Acknowledgement unavailable' } }));
  await page.goto('/calendar/events/' + publicId); await page.getByRole('checkbox', { name: 'Ana Two · shared@example.test' }).check();
  await page.getByRole('button', { name: 'Save reviewed context' }).click(); await page.getByRole('button', { name: 'Confirm event links' }).click(); await expect(page.getByRole('button', { name: 'Retry unchanged event change' })).toBeVisible();
  currentEpoch = '8a7fbd7f-9d0b-4f06-b7af-18c9be9ef8bc'; restoring = true; event = { ...event, people: [], plans: [], source_status: 'review_required' };
  await page.reload(); await expect(page.getByText('Recovery changed this workspace. Previous draft choices were cleared; review the current links before saving.')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Retry unchanged event change' })).toHaveCount(0); await expect(page.getByRole('checkbox', { name: 'A different restored person · shared@example.test' })).not.toBeChecked(); await expect(page.getByRole('checkbox', { name: 'Call Ana · Ana One · 2026-10-05' })).not.toBeChecked();
  await page.getByRole('checkbox', { name: 'A different restored person · shared@example.test' }).check(); currentEpoch = '7b0930f6-6289-4333-9751-39a2cbdc4488'; await page.getByRole('button', { name: 'Refresh current event' }).click(); await expect(page.getByRole('checkbox', { name: 'A different restored person · shared@example.test' })).not.toBeChecked();
});
