export const DATABASE_SCHEMA_VERSION = '8';
export const DATABASE_SCHEMA_VERSION_KEY = 'schema-version';

export const REQUIRED_TABLE_COLUMNS: Record<string, readonly string[]> = {
  app_metadata: ['key', 'value', 'updated_at'],
  workspaces: ['id', 'name', 'plan', 'persona', 'created_at'],
  contacts: [
    'id',
    'name',
    'nickname',
    'email',
    'phone',
    'photo_url',
    'birthday',
    'birthday_reminder_days',
    'how_we_met',
    'tags',
    'notes',
    'gift_ideas',
    'custom_fields',
    'contact_methods',
    'last_contacted',
    'contact_frequency',
    'created_at',
    'updated_at',
  ],
  contact_relationships: [
    'id',
    'contact_id',
    'related_contact_id',
    'relationship_label',
    'reciprocal_label',
    'created_at',
  ],
  contact_children: ['id', 'contact_id', 'linked_contact_id', 'name', 'birthday', 'created_at', 'updated_at'],
  contact_groups: ['id', 'name', 'color', 'created_at'],
  interactions: ['id', 'contact_id', 'date', 'type', 'summary', 'notes', 'created_at'],
  reminders: ['id', 'contact_id', 'title', 'notes', 'remind_at', 'completed_at', 'created_at'],
  daily_snoozes: ['id', 'contact_id', 'reminder_id', 'until_date', 'created_at', 'updated_at'],
  contact_group_members: ['contact_id', 'group_id'],
  relationship_facts: [
    'id',
    'contact_id',
    'category',
    'label',
    'value',
    'source',
    'confidence',
    'last_verified_at',
    'created_at',
  ],
  integration_connections: [
    'id',
    'workspace_id',
    'provider',
    'label',
    'status',
    'account_email',
    'last_synced_at',
    'sync_frequency_minutes',
    'metadata',
    'created_at',
    'updated_at',
  ],
  sync_jobs: [
    'id',
    'workspace_id',
    'provider',
    'job_type',
    'status',
    'summary',
    'started_at',
    'finished_at',
    'metadata',
  ],
  plans: [
    'id',
    'contact_id',
    'type',
    'planned_date',
    'summary',
    'notes',
    'completed_at',
    'created_at',
  ],
  contact_source_links: ['id', 'public_id', 'workspace_id', 'contact_id', 'provider', 'account_key', 'external_id', 'profile_url', 'origin', 'fields', 'revision', 'observed_at', 'created_at', 'updated_at'],
};

export const RESTORABLE_TABLES = [
  'app_metadata',
  'workspaces',
  'contacts',
  'contact_relationships',
  'contact_children',
  'contact_groups',
  'interactions',
  'reminders',
  'daily_snoozes',
  'contact_group_members',
  'relationship_facts',
  'integration_connections',
  'sync_jobs',
  'plans',
  'contact_source_links',
] as const;

export const DELETE_TABLE_ORDER = [...RESTORABLE_TABLES].reverse();
