/** Everclose Modern + Warm. Shared by web and native; no platform dependencies. */
export const colors = {
  canvas: '#FCF8F3',
  surface: '#FFFDFA',
  surfaceWarm: '#F5EEE7',
  ink: '#2C2527',
  muted: '#736667',
  faint: '#736667',
  line: '#E8DFD8',
  input: '#9C8077',
  primary: '#B72C52',
  primaryPressed: '#94223F',
  primarySoft: '#F9E3E8',
  moss: '#24664B',
  mossSoft: '#E4EFE7',
  amber: '#865116',
  amberSoft: '#FBEDD2',
  danger: '#AA2929',
  dangerSoft: '#FBE7E3',
  info: '#335572',
  infoSoft: '#EAF0F5',
  white: '#FFFFFF',
  rose: '#F8E0E4',
  roseInk: '#9A2E4A',
  sage: '#E6EBDD',
  sageInk: '#46533B',
  peach: '#FFE2CE',
  peachInk: '#8B482A',
  lavender: '#EBE4F3',
  lavenderInk: '#66507C',
  sky: '#E2EDF1',
  skyInk: '#345B6C',
} as const;

export const spacing = { xs: 4, sm: 8, md: 12, lg: 16, xl: 20, xxl: 24, section: 32, page: 40, hero: 48 } as const;
export const radii = { small: 8, control: 12, card: 20, dialog: 24, pill: 999 } as const;
export const typeScale = {
  title: { fontSize: 32, lineHeight: 40, fontWeight: '700', letterSpacing: -0.8 },
  section: { fontSize: 20, lineHeight: 28, fontWeight: '600', letterSpacing: -0.3 },
  body: { fontSize: 16, lineHeight: 24, fontWeight: '400' },
  label: { fontSize: 15, lineHeight: 22, fontWeight: '600' },
  caption: { fontSize: 13, lineHeight: 20, fontWeight: '400' },
} as const;
export const motion = { fast: 120, standard: 180, enter: 240 } as const;
export const targets = { minimum: 44, comfortable: 48 } as const;
export const elevation = {
  card: '0 4px 24px -12px rgb(85 48 55 / 0.18)',
  overlay: '0 16px 48px -16px rgb(44 37 39 / 0.22)',
  nativeCard: { shadowColor: '#553037', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 2 },
} as const;

export const avatarTones = [
  { background: colors.rose, foreground: colors.roseInk, className: 'bg-rose-soft text-rose-ink' },
  { background: colors.sage, foreground: colors.sageInk, className: 'bg-sage-soft text-sage-ink' },
  { background: colors.peach, foreground: colors.peachInk, className: 'bg-peach-soft text-peach-ink' },
  { background: colors.lavender, foreground: colors.lavenderInk, className: 'bg-lavender-soft text-lavender-ink' },
  { background: colors.sky, foreground: colors.skyInk, className: 'bg-sky-soft text-sky-ink' },
] as const;

/** Stable presentation color only; never an indicator of relationship health. */
export function avatarTone(name: string) {
  const hash = Array.from(name.normalize('NFC')).reduce((sum, char) => sum + char.codePointAt(0)!, 0);
  return avatarTones[hash % avatarTones.length];
}

const semanticColors = {
  background: colors.canvas, foreground: colors.ink, card: colors.surface,
  'card-foreground': colors.ink, primary: colors.primary, 'primary-foreground': colors.white,
  secondary: colors.primarySoft, 'secondary-foreground': colors.primary,
  muted: colors.surfaceWarm, 'muted-foreground': colors.muted,
  accent: colors.surfaceWarm, 'accent-foreground': colors.ink,
  destructive: colors.danger, 'destructive-foreground': colors.white,
  border: colors.line, input: colors.input, ring: colors.primary,
  success: colors.moss, 'success-soft': colors.mossSoft,
  warning: colors.amber, 'warning-soft': colors.amberSoft,
  info: colors.info, 'info-soft': colors.infoSoft, 'danger-soft': colors.dangerSoft,
  'rose-soft': colors.rose, 'rose-ink': colors.roseInk,
  'sage-soft': colors.sage, 'sage-ink': colors.sageInk,
  'peach-soft': colors.peach, 'peach-ink': colors.peachInk,
  'lavender-soft': colors.lavender, 'lavender-ink': colors.lavenderInk,
  'sky-soft': colors.sky, 'sky-ink': colors.skyInk,
} as const;

function hsl(hex: string) {
  const [r, g, b] = [1, 3, 5].map((start) => parseInt(hex.slice(start, start + 2), 16) / 255);
  const max = Math.max(r, g, b), min = Math.min(r, g, b), delta = max - min, lightness = (max + min) / 2;
  const hue = !delta ? 0 : max === r ? ((g - b) / delta + (g < b ? 6 : 0)) * 60
    : max === g ? ((b - r) / delta + 2) * 60 : ((r - g) / delta + 4) * 60;
  const saturation = !delta ? 0 : delta / (1 - Math.abs(2 * lightness - 1));
  return `${Number(hue.toFixed(2))} ${Number((saturation * 100).toFixed(2))}% ${Number((lightness * 100).toFixed(2))}%`;
}

export function createThemeCss() {
  const values = Object.entries(semanticColors).map(([key, color]) => `    --${key}: ${hsl(color)};`);
  return `/* Generated by npm run design:tokens from packages/design/src/tokens.ts. */\n:root {\n${values.join('\n')}\n    --radius: ${radii.control / 16}rem;\n    --shadow-card: ${elevation.card};\n    --shadow-overlay: ${elevation.overlay};\n    --motion-fast: ${motion.fast}ms;\n    --motion-standard: ${motion.standard}ms;\n    --motion-enter: ${motion.enter}ms;\n}\n`;
}
