import * as ImagePicker from 'expo-image-picker';
import { ImageManipulator, SaveFormat } from 'expo-image-manipulator';
import { File, Paths } from 'expo-file-system';
import { CONTACT_PHOTO_DIMENSION, MAX_CONTACT_PHOTO_SOURCE_BYTES, isEmbeddedContactPhoto } from '../../../../packages/domain/src/contact-photo';

function removeTemporary(uri: string) {
  // Only files generated by these two native modules in our app cache are ours to remove.
  if (uri.startsWith(Paths.cache.uri.replace(/\/+$/u, '') + '/') && /\/(?:ImagePicker|ImageManipulator)\//u.test(uri)) {
    try { const file = new File(uri); if (file.exists) file.delete(); } catch { /* A later cache cleanup can remove it. */ }
  }
}
export async function chooseContactPhoto(isCurrent: () => boolean) {
  const picked = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: false, quality: 1 });
  if (picked.canceled) return null;
  const asset = picked.assets[0];
  if (!isCurrent()) { removeTemporary(asset.uri); return null; }
  let context: ReturnType<typeof ImageManipulator.manipulate> | null = null;
  let image: Awaited<ReturnType<ReturnType<typeof ImageManipulator.manipulate>['renderAsync']>> | null = null;
  try {
    const size = asset.fileSize ?? new File(asset.uri).size;
    if (!Number.isSafeInteger(size) || size <= 0 || size > MAX_CONTACT_PHOTO_SOURCE_BYTES
      || !Number.isSafeInteger(asset.width) || !Number.isSafeInteger(asset.height)
      || asset.width < 1 || asset.height < 1 || asset.width * asset.height > 40_000_000) throw new Error('Choose a photo under 10 MB and 40 megapixels.');
    const edge = Math.min(asset.width, asset.height);
    context = ImageManipulator.manipulate(asset.uri);
    context.crop({ originX: Math.floor((asset.width - edge) / 2), originY: Math.floor((asset.height - edge) / 2), width: edge, height: edge })
      .resize({ width: CONTACT_PHOTO_DIMENSION, height: CONTACT_PHOTO_DIMENSION });
    image = await context.renderAsync();
    for (const compress of [0.82, 0.6]) {
      const result = await image.saveAsync({ format: SaveFormat.JPEG, compress, base64: true });
      removeTemporary(result.uri);
      const photo = `data:image/jpeg;base64,${result.base64 ?? ''}`;
      if (isEmbeddedContactPhoto(photo)) return isCurrent() ? photo : null;
    }
    throw new Error('This photo is too large after resizing. Choose another image.');
  } finally { image?.release(); context?.release(); removeTemporary(asset.uri); }
}
